name: my_portfolio
description: devShakib Portfolio.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  animated_text_kit: ^4.2.3
  font_awesome_flutter: ^10.9.0
  url_launcher: ^6.3.2
  percent_indicator: ^4.2.5
  animations: ^2.0.11
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/works/


flutter_native_splash:
  color: "#36B799"
  image: assets/images/splash.png
  web_image_mode: center